"""
Database wrapper for auto_trader - replaces JSON file operations with Supabase
"""
from utils.trades_db import (
    get_user_trades, save_trade, update_trade_sell, delete_trade
)
import logging

logger = logging.getLogger("auto_trader")

# Global context: which user is currently running auto-trader
# Used as fallback if user_id not provided explicitly  
_current_user_id = None


def set_auto_trader_user_id(user_id):
    """Set the user context for trades being generated
    
    Used as fallback for auto-trader instances that don't pass user_id directly.
    """
    global _current_user_id
    _current_user_id = user_id
    logger.info(f"Auto-trader user context set to: {user_id}")


def clear_auto_trader_user_id():
    """Clear the user context"""
    global _current_user_id
    _current_user_id = None


def get_auto_trader_user_id():
    """Get current auto-trader user context"""
    return _current_user_id


def load_trades_for_autotrader(user_id=None):
    """
    Load all trades for the specified user or current auto-trader user
    
    Args:
        user_id: Optional user ID. If not provided, uses global _current_user_id
    """
    if user_id is None:
        user_id = _current_user_id
    
    if not user_id:
        logger.warning("No user context set for auto-trader")
        return []
    
    try:
        trades = get_user_trades(user_id)
        logger.info(f"Loaded {len(trades)} trades for user {user_id}")
        return trades
    except Exception as e:
        logger.error(f"Error loading trades: {e}")
        return []


def save_auto_trade(trade: dict, user_id=None) -> dict:
    """
    Save a trade generated by auto-trader
    Automatically adds user_id from context or explicit parameter
    
    Args:
        trade: Trade dict to save
        user_id: Optional explicit user ID. If not provided, uses global _current_user_id
    """
    if user_id is None:
        user_id = _current_user_id
    
    if not user_id:
        raise ValueError("No user context set - cannot save auto-trader trade")
    
    try:
        trade = dict(trade)  # Copy to avoid modifying original
        trade['user_id'] = int(user_id)
        
        saved = save_trade(trade)
        logger.info(f"Saved auto-trade: {trade.get('name')} for user {user_id}")
        return saved
    except Exception as e:
        logger.error(f"Error saving auto-trade: {e}")
        raise


def update_auto_trade_sell(trade_id: str, sell_price: float, sell_time: str, reason: str = "", user_id=None) -> dict:
    """
    Close an auto-trade with sell price
    
    Args:
        trade_id: ID of trade to close
        sell_price: Selling price
        sell_time: Selling time
        reason: Reason for closing
        user_id: Optional explicit user ID. If not provided, uses global _current_user_id
    """
    if user_id is None:
        user_id = _current_user_id
    
    if not user_id:
        raise ValueError("No user context set")
    
    try:
        result = update_trade_sell(trade_id, user_id, sell_price, sell_time, reason)
        if result:
            logger.info(f"Closed auto-trade {trade_id} - P&L: {result.get('pnl')} - Reason: {reason}")
            return result
        else:
            logger.warning(f"Failed to close trade {trade_id} - unauthorized or not found")
            return None
    except Exception as e:
        logger.error(f"Error closing auto-trade: {e}")
        raise


def delete_auto_trade(trade_id: str, user_id=None) -> bool:
    """Delete an auto-trade
    
    Args:
        trade_id: ID of trade to delete
        user_id: Optional explicit user ID. If not provided, uses global _current_user_id
    """
    if user_id is None:
        user_id = _current_user_id
    
    if not user_id:
        raise ValueError("No user context set")
    
    try:
        success = delete_trade(trade_id, user_id)
        if success:
            logger.info(f"Deleted auto-trade {trade_id}")
        return success
    except Exception as e:
        logger.error(f"Error deleting trade: {e}")
        return False
